name: Cucumber Developer User Role Default
description: A recipe to manage default configs for the Cucumber Developer User Role.
type: Testing
config:
  actions:
    cucumber_user_roles.settings:
      simple_config_update:
        developer: true
    user_redirect.settings:
      simple_config_update:
        login.developer.redirect_url: '/dashboard/developer_dashboard'
        logout.developer.redirect_url: '/user/login'
    user.role.admin:
      grantPermissions:
        - 'can view developer_dashboard dashboard'
