name: Cucumber Coordinator User Role Default
description: A recipe to manage default configs for the Cucumber Coordinator User Role.
type: Testing
config:
  actions:
    cucumber_user_roles.settings:
      simple_config_update:
        coordinator: true
    user.role.admin:
      grantPermissions:
        - 'can view coordinator_dashboard dashboard'
