name: Cucumber Tester User Role Default
description: A recipe to manage default configs for the Cucumber Tester User Role.
type: Testing
config:
  actions:
    cucumber_user_roles.settings:
      simple_config_update:
        tester: true
    user.role.admin:
      grantPermissions:
        - 'can view tester_dashboard dashboard'
