name: Cucumber Analyst User Role Default
description: A recipe to manage default configs for the Cucumber Analyst User Role.
type: Testing
config:
  actions:
    cucumber_user_roles.settings:
      simple_config_update:
        analyst: true
    user.role.admin:
      grantPermissions:
        - 'can view analyst_dashboard dashboard'
