name: Cucumber Analyst User Role Default
description: A recipe to manage default configs for the Cucumber Analyst User Role.
type: Testing
config:
  actions:
    cucumber_user_roles.settings:
      simple_config_update:
        analyst: true
    user_redirect.settings:
      simple_config_update:
        login.analyst.redirect_url: '/dashboard/analyst_dashboard'
        logout.analyst.redirect_url: '/user/login'
    user.role.admin:
      grantPermissions:
        - 'can view analyst_dashboard dashboard'
